// <auto-generated />
using System;
using CavistaLaptopLifecycleManagement.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CavistaLaptopLifecycleManagement.Api.Migrations
{
    [DbContext(typeof(CLMDbContext))]
    [Migration("20260902155700_ChangeRoleName")]
    partial class ChangeRoleName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ActionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ActionBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActionOnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails", (string)null);
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.LaptopHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActionBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserLaptopHistoryStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserLaptopID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserLaptopID");

                    b.ToTable("LaptopHistories", (string)null);
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActionBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("TicketHistoryStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TicketID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserLaptopID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketID");

                    b.HasIndex("UserLaptopID");

                    b.ToTable("TicketHistories");
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.UserLaptop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DepreciationEstimationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeDepartment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EstimationUsefulLifeYear")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("PurchaseYear")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("WarrantyExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("UserLaptops", (string)null);
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.LaptopHistory", b =>
                {
                    b.HasOne("CavistaLaptopLifecycleManagement.Api.Database.Entities.UserLaptop", "UserLaptop")
                        .WithMany("LaptopHistories")
                        .HasForeignKey("UserLaptopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserLaptop");
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.TicketHistory", b =>
                {
                    b.HasOne("CavistaLaptopLifecycleManagement.Api.Database.Entities.Ticket", "Ticket")
                        .WithMany("TicketHistories")
                        .HasForeignKey("TicketID");

                    b.HasOne("CavistaLaptopLifecycleManagement.Api.Database.Entities.UserLaptop", "UserLaptop")
                        .WithMany()
                        .HasForeignKey("UserLaptopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("UserLaptop");
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.UserLaptop", b =>
                {
                    b.HasOne("CavistaLaptopLifecycleManagement.Api.Database.Entities.User", "User")
                        .WithMany("UserLaptops")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.Ticket", b =>
                {
                    b.Navigation("TicketHistories");
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.User", b =>
                {
                    b.Navigation("UserLaptops");
                });

            modelBuilder.Entity("CavistaLaptopLifecycleManagement.Api.Database.Entities.UserLaptop", b =>
                {
                    b.Navigation("LaptopHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
